language: haskell

env:
  - GHCVER=7.4.2
  - GHCVER=7.6.3
  - GHCVER=7.8.3

before_install:
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update
  - sudo apt-get install -y -qq cabal-install-1.18 ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.18/bin:$PATH

install:
  - cabal sandbox init
  - cabal install --only-dependencies

script:
  - cabal configure
  - cabal build
